// src/components/Footer.svelte
<footer id="footer" class="footer position-relative">
    <div class="container">
      <h3 class="sitename">Feri Irawansyah</h3>
      <!-- <p>.</p> -->
      <div class="social-links d-flex justify-content-center">
        <a href="https://www.linkedin.com/in/feri-irawansyah/" target="_blank"  aria-label="Linkedin"><i class="bi bi-linkedin"></i></a>
        <a href="https://github.com/snakesystem/" aria-label="Github" target="_blank"><i class="bi bi-github"></i></a>
        <a href="https://www.instagram.com/fery_ir.1/" target="_blank"  aria-label="Instagram"><i class="bi bi-instagram"></i></a>
        <a href="https://www.facebook.com/fery.irawansyah.58/" target="_blank" aria-label="Facebook"><i class="bi bi-facebook"></i></a>
        <a href="https://x.com/snakesystem" target="_blank" aria-label="Twitter"><i class="bi bi-twitter-x"></i></a>
      </div>
      <div class="container">
        <div class="copyright">
          <span>&copy; <a href="https://github.com/snakesystem"><strong class="px-1 sitename">Feri Irawansyah</strong></a></span>
        </div>
        <div class="credits">
          Powered by <a target="_blank" href="https://svelte.dev">Svelte</a>, <a target="_blank"  href="https://vite.dev/">Vite</a> & <a target="_blank"  href="https://www.rust-lang.org">Rust</a>— Distributed with ❤️
        </div>
      </div>
    </div>
  </footer>

// src/components/Footer.tsx

export default function Footer() {
  return (
    <footer id="footer" className="footer position-relative light-background">

        <div className="container">
        <div className="copyright text-center ">
            <p>© <span>Copyright</span> <strong className="px-1 sitename">iPortfolio</strong> <span>All Rights Reserved</span></p>
        </div>
        <div className="credits">
            <img src="/img/logo-ss.png" alt="" />
            <a href="https://github.com/Snakesystem">Snakesystem</a>
        </div>
        </div>

    </footer>
  )
}
